version: 2.1

description: |
  Simplify ansible
executors:
  default:
    description: |
      Custom Docker image with pre-packaged welcome orb commands
    docker:
    - image: alpine:latest

jobs:
  ansible-lint:
    description: Run ansible lint
    executor: default
    parameters:
      config:
        description: Specify a custom ansible-lint config
        type: string
    steps:
    - run: 
        name: Install packages needed
        command: apk --no-cache add python3 ansible-lint
    - checkout
    - run: 
        name: Check ansible lint version
        command: ansible-lint --version
    - when:
        condition: <<parameters.config>>
        steps:
          - run: 
              name: Run ansible lint
              command: find ./ansible -type f -name '*.yml' | xargs ansible-lint -c <<parameters.config>>
    - unless:
        condition: <<parameters.config>>
        steps:
          - run: 
              name: Run ansible lint
              command: find ./ansible -type f -name '*.yml' | xargs ansible-lint