version: 2.1

description: |
  Simplify ansible
executors:
  default:
    description: |
      Custom Docker image with pre-packaged welcome orb commands
    docker:
    - image: circleci/welcome-config-image:0.2.1

jobs:
  ansible-lint:
    description: Run ansible lint
    executor: default
    parameters:
        config:
          default: ~/project
          description: Path to the directory containing your package.json file. Not
            needed if package.json lives in the root.
          type: string
    steps:
    - checkout
    - run: 
        name: Check ansible lint version
        command: ansible-lint --version
    - when:
        condition: <<parameters.config>>
        steps:
          - run: 
            name: Run ansible lint
            command: find ./ansible -type f -name '*.yml' | xargs ansible-lint -c <<parameters.config>>
    - unless:
        condition: <<parameters.config>>
        steps:
          - run: 
              name: Run ansible lint
              command: find ./ansible -type f -name '*.yml' | xargs ansible-lint